- hosts: localhost
  tasks:
  - name: clone nvm
    ansible.builtin.git:
      repo: https://github.com/lukechilds/zsh-nvm 
      dest: ~/.oh-my-zsh/custom/plugins/zsh-nvm
  
  - name: load zsh plugin
    ansible.builtin.lineinfile:
      path: /home/vagrant/.zshrc
      line: plugins+=(zsh-nvm)
      insertbefore: source $ZSH/oh-my-zsh.sh

  - name: configure lazy loading
    ansible.builtin.lineinfile:
      path: /home/vagrant/.zshrc
      line: export NVM_LAZY_LOAD=true
      
