- hosts: localhost
  tasks:
  - name: clone nvm
    ansible.builtin.git:
      repo: https://github.com/lukechilds/zsh-nvm 
      dest: ~/.oh-my-zsh/custom/plugins/zsh-nvm
  
  - name: load zsh plugin
    ansible.builtin.blockinfile:
      path: "/home/{{ username }}/.zshrc"
      marker: "# {mark} ANSIBLE MANAGED nvm BLOCK"
      block: |
        export NVM_LAZY_LOAD=true
        plugins+=(zsh-nvm)
      insertbefore: source \$ZSH/oh-my-zsh.sh


