- hosts: localhost
  tasks:
  - name: "copy initial p10k config"
    ansible.builtin.copy:
      src: "{{ playbook_dir }}/files/p10k.zsh"
      dest: "/home/{{ username }}/.p10k.zsh"
      mode: 0644

  - name: "instantpromt p10k.zsh"
    ansible.builtin.blockinfile:
      path: "/home/{{ username }}/.zshrc"
      marker: "# {mark} ANSIBLE MANAGED BEGIN BLOCK"
      block: |
        # Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
        # Initialization code that may require console input (password prompts, [y/n]
        # confirmations, etc.) must go above this block; everything else may go below.
        if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
          source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
        fi
      insertbefore: BOF

  - name: "customizations p10k.zsh"
    ansible.builtin.blockinfile:
      path: "/home/{{ username }}/.zshrc"
      marker: "# {mark} ANSIBLE MANAGED END BLOCK"
      block: |
        # To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
        [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
      insertafter: EOF
