- hosts: localhost
  tasks:
    - name: Install vim
      become: True
      package:
        name: vim
      loop:
      - vim
      - build-essentials
      - cmake

    - name: Install Vundle
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: "/home/{{ username }}/.vim/bundle/Vundle.vim"
    - name: copy vimrc
      copy:
        src: "vimrc"
        dest: "/home/{{ username }}/.vimrc"
      notify: plugins update

  handlers:
    - name: "plugins update"
      import_tasks: tasks/vim-plugin-update.yml
