- hosts: localhost
  tasks:
    - name: Install vim
      become: True
      package:
        name: vim

    - name: Install Vundle
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: "/home/{{ username }}/.vim/bundle/Vundle.vim"
    - name: copy vimrc
      copy:
        src: "vimrc"
        dest: "/home/{{ username }}/.vimrc"
      register: vimrc

    - name: Clean Plugins
      command: vim +PluginClean +qall
      when: "vimrc is changed"

    - name: Install Plugins
      command: vim +PluginInstall +qall
      when: "vimrc is changed"

    - name: Update Plugins
      command: vim +PluginUpdate +qall
      when: "vimrc is changed"

    - name: "compile YouCompleteMe"
      block: 
      - name: link file
        ansible.builtin.file: 
          state: link
          src: /usr/bin/gcc
          dest: /usr/bin/gcc-5
        become: True
      - name: run install.py
        ansible.builtin.command:
          cmd: install.py
          chdir: /home/vagrant/.vim/bundle/YouCompleteMe


      

