- hosts: localhost
  tasks:
    - name: Install vim
      become: True
      package:
        name: vim

    - name: Install Vundle
      git:
        repo: https://github.com/gmarik/Vundle.vim.git
        dest: "/home/{{ username}}/.vim/bundle/Vundle.vim"
    - name: copy vimrc
      copy:
        src: "vimrc"
        dest: "/home/{{ username }}/.vimrc"
      register: vimrc

    - name: Clean Plugins
      command: vim +PluginClean +qall
      when: "vimrc is changed"

    - name: Install Plugins
      command: vim +PluginInstall +qall
      when: "vimrc is changed"

    - name: Update Plugins
      command: vim +PluginUpdate +qall
      when: "vimrc is changed"
